### ISSUE TITLE
24H2 - Access denied when disabling Windows Defender

### ISSUE THREAD

**Issue by tinodin** [valleyofdoom/service-list-builder#2]
Starting with 24H2 TrustedInstaller no longer has permission to change the values of these services: WinDefend, WdNisDrv and WdNisSvc. A current workaround is to manually disable Windows Defender beforehand but this is very tedious to do when regularly switching between service states. So if anyone is able to find a fix, please let me know.

Here is the output:

service-list-builder>reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\WinDefend" /v "Start" /t REG_DWORD /d "4" /f
ERROR: Access is denied.

service-list-builder>reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\WdNisDrv" /v "Start" /t REG_DWORD /d "4" /f
ERROR: Access is denied.

service-list-builder>reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\WdNisSvc" /v "Start" /t REG_DWORD /d "4" /f
ERROR: Access is denied.

**Comment by valleyofdoom** [comment]
> Starting with 24H2 TrustedInstaller no longer has permission to change the values of these services

This was the case for earlier versions too, it's nothing new for 24H2. To resolve the access denied error you need to disable tamper protection and/or real-time protection.
